### PR TITLE
Release notes for Fusion.

### PR DESCRIPTION
**Pull request by Flast**
Hi @djowel , @K-ballo and @daminetreg !

Here is 1.59.0 release notes for Fusion. Could you review this?

### CODE REVIEW

**Comment by djowel** [comment]
Looks good to me.

**Comment by daminetreg** [comment]
Looks good to me too. :) Sad that I couldn't finish the testing of the removal of BOOST_PP_IS_EMPTY ‎to avoid warnings in MSVC 8 for this release.                                                                                                                                                                                                                                                                                                                                        --Damien Buhl                                                                                                                                                                                                                From: Joel de GuzmanSent: samedi 18 juillet 2015 10:58To: boostorg/websiteReply To: boostorg/websiteCc: Damien BuhlSubject: Re: [website] Release notes for Fusion. (#91)Looks good to me. 

—Reply to this email directly or view it on GitHub.

**Comment by Flast** [comment]
Thank you both!

@danieljames , could you merge this?

**Comment by Flast** [comment]
Thank you @grafikrobot !

**Comment by djowel** [comment]
Thanks Rene!

**Pull request merged**
