### PR TITLE
Json changelog

### PR DESCRIPTION
**Pull request by grisumbras**

### CODE REVIEW

**Comment by grisumbras** [comment]
@vinniefalco can you look at this PR?

**Comment by vinniefalco** [comment]
We need to determine if there are security-related fixes. For example were there any changes to the parser that fix vulnerabilities? You might look at the history for just the parser related files. And after we get the Bishop Fox report, I will want to link to it right in the release notes. I can submit that pull request later. And we'll also want to link the report in the docs (I can do that too).

**Comment by grisumbras** [comment]
No, the potential issue with parsing was not addressed in changes that go into this release. This would have to be a semantic change (producing an error when parsing numbers that we cannot represent rather than producing 0 or infinity).

**Comment by vinniefalco** [comment]
Looks good

**Pull request merged**
