### PR TITLE
new library fiber

### PR DESCRIPTION
**Pull request by olk**

### CODE REVIEW

**Comment by olk** [comment]
I assume the content is generated  from fiber/meta/libraries.json

**Comment by olk** [comment]
sorry - was too eager to close unnecessary pull requests

**Comment by danieljames** [comment]
Not exactly. I have a script which lists the new libraries, but I manage this manually as sometimes people want to put something different in the release notes.

**Comment by danieljames** [comment]
That's no problem, I'd somehow missed this one.

**Pull request merged**
