### PR TITLE
Add a note about the upcoming breaking change in Boost.Atomic

### PR DESCRIPTION
**Pull request by Lastique**

### CODE REVIEW

**Comment by danieljames** [comment]
We can also change the documentation on the website if you want. Just need to add the updated pages to https://github.com/boostorg/documentation-fixes.

**Comment by Lastique** [comment]
Thanks.

Yes, updating the docs would be nice. I've created a branch with the updated docs:

https://github.com/boostorg/atomic/tree/1.66.0-backports

The only change compared to 1.66.0 is this:

https://github.com/boostorg/atomic/commit/eb13eed01959ef368935329c7288ca06085d6f09

The added content is generated in libs/atomic/doc/html/atomic/interface.html. I've attached the file that I generated locally.

[interface.html.gz](https://github.com/boostorg/website/files/1678728/interface.html.gz)

**Comment by danieljames** [comment]
Should be updated now.

**Comment by Lastique** [comment]
Thanks again, Daniel.

**Pull request merged**
