### PR TITLE
Add Boost.Utility release notes

### PR DESCRIPTION
**Pull request by Lastique**

### CODE REVIEW

**Comment by danieljames** [comment]
Was this was added after the beta? If so, I'm going to wait a few days before merging, to give people a chance to make last minute changes to the beta notes.

**Comment by Lastique** [comment]
The change was merged to master today, after the beta.

**Comment by danieljames** [comment]
Should be rebuilt in the next hour at: http://www.boost.org/users/history/in_progress.html

**Comment by Lastique** [comment]
Thanks.

**Pull request merged**
